### ISSUE TITLE
identify which fields can be faceted by the GDC

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#100]
Related to https://github.com/wmo-im/wis2-guide/issues/10, the GDC should have a clear list of what WCMP2 properties can be faceted.

The results should be (in the following order):
- [ ] WCMP2: an annex with a list of fields/JSON Paths that a GDC should consider for faceting
- [ ] WIS2 Guide: directives on how a GDC should facet per the WCMP2 annex

**Comment by antje-s** [comment]
suggestion as starting point:

- id (country and centre-id part) as originator
- geometry (area/bbox)
- properties/type (list of values)
- properties/wmo:dataPolicy (list of values)
- properties/formats (list of values)
- properties/contacts/organization (list of values)
- properties/created (before/after date OR lastWeek/lastMonth/thisYear)
- properties/updated (before/after date OR lastWeek/lastMonth/thisYear)

**Comment by amilan17** [comment]
[https://github.com/wmo-im/tt-wismd/wiki/Meeting-2023-08-14](https://github.com/wmo-im/tt-wismd/wiki/Meeting-2023-08-14) notes 

this would be a section in the guide that a catalog should do these facets at a minimum. Note that indexing is an implementation detail that may vary depending on the type of software.

**Comment by antje-s** [comment]
as a minimum I would reduce facets further to:

- originator (country, centre-id)
- properties/type 
- wmo:dataPolicy

(& adding a note on various possible search variants like full text search, date search (before/after), geometry search)

**Comment by tomkralidis** [comment]
Thanks @antje-s for the analysis.  A PR in #114 has been put forth for review and comment, along with https://github.com/wmo-im/wis2-guide/pull/25.
