### ISSUE TITLE
support WCMP2 records for services

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#102]
WCMP2 is designed to encompass any resource (which means any type of dataset, service, process, etc.) (note: see https://github.com/wmo-im/wcmp2-codelists/blob/main/codelists/resource-type.csv for supported resource types for `properties.type`).

For WIS2, we should have service metadata (so `properties.type="service"`) for the following services in the GDC proper:

- Global Cache
- Global Broker
- Global Discovery Catalogue
- Global Monitoring

This will primarily allow the GDC to encompass all Global Services when publishing WCMP2 records with accurate and complete information for GB, GC, etc.

Note that as APIs proliferate across the WIS2 ecosystem, it would be valuable to provide some guidance/best practice in this regard as well.

Now, having said this, in WIS2 (and beyond) we are moving from a Service-Oriented Architecture (SOA) to a Resource-Oriented Architecture (ROA).  For WCMP2/GDC this means discovery and metadata is **data** driven, and that a dataset's record will have the services listed accordingly (data -> service binding).

Initial thoughts:
- a Global Discovery Catalogue or Global Cache could be realized with a simple WCMP2 record with the canonical/self link being the endpoint itself
- a Global Broker should ideally advertise itself via an [AsyncAPI](https://www.asyncapi.com), to leverage already existing standards
- Web APIs should ideally advertise via an [OpenAPI](https://www.openapis.org/) description, to leverage already existing standards

Looking forward to hearing others' thoughts.

**Comment by amilan17** [comment]
Should a metadata record for a GC list the types/sources/etc of data that is in the cache? 
For example, all of the topics available from that GC, TH levels 1-8...,  or a list of countries and programs?

**Comment by tomkralidis** [comment]
I would contain to only service metadata, and let the WCMP2 dataset records and GDC allow for resource-based discovery.

**Comment by tomkralidis** [comment]
>> Should a metadata record for a GC list the types/sources/etc of data that is in the cache? For example, all of the topics available from that GC, TH levels 1-8..., or a list of countries and programs?

> It would contain only service metadata, and let the WCMP2 dataset records and the GDC allow for resource-based discovery.

Correction/update: for non-WIS2 use cases it would be valuable to list the Earth System Disciplines.  This (and other requirements/recommendations/permissions) has been put forth as part of #110 for review.
