### ISSUE TITLE
clarify URI scheme to use for MQTT links

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#105]
WCMP2 records will provide links to MQTT endpoints.  Neither `mqtt://` or `mqtts://` seem to be registered IANA URI schemes.

As an example the [mosquitto man page](https://mosquitto.org/man/mosquitto_sub-1.html) `mqtt://` (default port 1883) and `mqtts://` (default port 8883).  One could also use `ssl://` or `tcp://` accordingly.  We should verify what others communities are using, as well as any discussions from OASIS and/or IANA.

The result of the above investigation/clarification will be a WCMP2 requirement for Pub/Sub links.

**Comment by josusky** [comment]
The `mqtt/mqtts` URI scheme is mentioned on GitHub of the mqtt.org (https://github.com/mqtt/mqtt.org/wiki/URI-Scheme) but somehow they did not make an effort to pass it to IANA.

**Comment by tomkralidis** [comment]
More information [here](https://github.com/mqtt/mqtt.org/issues/41).

**Comment by tomkralidis** [comment]
PR in #106
