### ISSUE TITLE
review and provide recommendation on future of WCMP

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#11]
# Summary and Purpose

## WCMP Status
- WCMP has been in existence since the creation of WIS (~2012)
- WCMP provides:
  - a profile based on ISO 19115/19139 (i.e. not a new model or schema)
  - an abstract test suite to help determine compliance
  - a dedicated set of custom codelists (some extending ISO 19115, some new/dedicated to WMO)
- KPIs have been implemented in support of WCMP quality assessment for GISCs

## WIS
- WIS 1.0 has been operational since ~2012
- WIS 2.0 principles (summary as part of [initial WIS 2.0 search pilot project](https://github.com/wmo-im/wis2-metadata-search/issues/1))
  - lower the barrier to entry
  - FAIR data principles
  - Web architecture/hypermedia
  - webby/of the web
  - search engine friendly
  - the browser is the search engine
  - schema.org

## Current landscape
- XML is slowly being replaced by JSON (of the web, tight coupling with programming language)
- mass market integration is a priority
- cross pollination with another information communities (extending the reach)
- Service-oriented architecture (SOA) -> Resource-oriented architecture (ROA)
- other organizations such as OGC are undergoing efforts to move to modernized approaches (i.e [OGC API](https://ogcapi.ogc.org))

# Proposal
@wmo-im/tt-wismd to assess and evaluate options for the future of WCMP against established criteria of requirements, e.g.:
- do nothing, use existing WCMP 1.3
- move to ISO 19115-3
- consider other metadata standards (DCAT2, OGC API - Records, etc.)

## Criteria
- WIS 2.0 alignment
- content
- migration
- backwards compatibility
- change management
- interoperability
- cross pollination with other communities
- timelines for WMO endorsement

# Reason
As TT-WISMD, we need to put forth next steps in realizing discovery in alignment with WIS 2.0 and current state.

cc @6a6d74 @joergklausen

**Comment by amilan17** [comment]
@tomkralidis I think we can close this

**Comment by tomkralidis** [comment]
Related https://github.com/wmo-im/wcmp2/issues/10#issuecomment-1556991851, OGC API - Records has been used as the baseline for WCMP2, and the Global Discovery Catalogue (GDC).
