### ISSUE TITLE
More detailed definition of link relation

### ISSUE THREAD

**Issue by josusky** [wmo-im/wcmp2#124]
In the WNM we have [requirements](https://github.com/wmo-im/wis2-notification-message/blob/main/standard/requirements/core/REQ_links.adoc) that explicitly lists allowed link relations.
One of them is from IANA (`canonical`) others are from WMO "namespace".
In [the requirement](https://github.com/wmo-im/wcmp2/blob/main/standard/requirements/core/REQ_links.adoc) for the links in metadata records, we somewhat vaguely refer to IANA and WCMP codelist.
Then in the examples, we present relations `download`, `subscribe`, and `items` which are **not** in the [IANA list](https://www.iana.org/assignments/link-relations/link-relations.xhtml).
* Could we replace `download` with `canonical` (to be compatible with IANA and WNM)?
* Could we replace `items` with `item` (to be compatible with IANA)? BTW, is this the one to be used for MQTT (pub-sub) services?
* We may keep using `search` (that one exists in IANA).
* If we need more/different types, shouldn't we define a WCMP2-specific code list, that would then use URL-like notation, e.g. `http://def.wmo.int/def/rel/wcmp/-/download]?

**Comment by amilan17** [comment]
Would the following be the equivalent of 'download'? 

<table><tbody><tr><td>dns-prefetch</td><td>Used to indicate an origin that will be used to fetch required resources for the link context, and that the user agent ought to resolve as early as possible.</td></tr></tbody></table>

**Comment by tomkralidis** [comment]
Notes:

- #125 (merged) defines  "list of lists" of acceptable link relations (i.e. IANA or WMO link types).  Note that the [2 link types](https://github.com/wmo-im/wcmp2-codelists/blob/main/codelists/link-type.csv#L6-L7) in the WMO link types codelist WITHOUT a WMO namespace are coming from the OGC API standards (they are duplicated here for convenience)
- #127 (needs review and approval) fixes all examples with valid link relations as a result

**Comment by tomkralidis** [comment]
Having said this, I've added a link relation table for guidance in this PR, for review (feel free to suggest additional examples).
