### ISSUE TITLE
add a requirement for dataset in type

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#142]
[https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.html#_properties_type](https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.html#_properties_type)

There is a requirement for 'service', but I think that we should explicitly state that dataset is required for data

**Comment by tomkralidis** [comment]
This is covered by Requirement 4B:

> A WCMP record’s properties.type property SHALL provide a valid resource type from the WCMP resource type codelist.

The associated codelist can be found in https://github.com/wmo-im/wcmp2-codelists/blob/main/codelists/resource-type.csv

**Comment by tomkralidis** [comment]
TT-WISMD 2023-12-01:
- add explanations on the different types
- remove Req 5A
- add more examples

**Comment by amilan17** [comment]
thanks!
