### ISSUE TITLE
snippets validation errors

### ISSUE THREAD

**Issue by josusky** [wmo-im/wcmp2#152]
I will collect errors identified during the validation of snippets - examples embedded in the WCMP2 specification:

1. clause_7_normative_text.adoc - Temporal Extent - Examples
```
"time": {
    "interval": [
        ["R/T00Z", "PT180H"],
        ["R/T12Z", "PT180H"]
    ],
    "resolution": "PT6H"
}
```
'errors: ["$.time: {\'interval\': [[\'R/T00Z\', \'PT180H\'], [\'R/T12Z\', \'PT180H\']], \'resolution\': \'PT6H\'} is not valid under any of the given schemas"]')

**Comment by josusky** [comment]
2. clause_7_normative_text.adoc - Example: complex time information with additional explanation and characteristics:
```
"time": {
    "interval": [
        ["T00Z", "PT180H"],
        ["T12Z", "PT180H"]
    ],
    "resolution": "PT6H"
}```

'errors: ["$.time: {\'interval\': [[\'T00Z\', \'PT180H\'], [\'T12Z\', \'PT180H\']], \'resolution\': \'PT6H\'} is not valid under any of the given schemas"]')

**Comment by josusky** [comment]
3. Additional Temporal Extents
```
"additionalExtents": {
  "temporal": {
    "interval": [
      [
        "1924-08-18",
        null
      ]
    ],
    "resolution": "P1H",
    "trs": "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"
  }
}
```
'errors: ["$.additionalExtents.temporal.interval[0][1]: None is not of type \'string\'"]'

**Comment by josusky** [comment]
3. Properties / Contacts
```
"properties": {
  ...
  "contacts": [{
      "identifier": "ECCC",
      "organization": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
      "positionName": "National Inquiry Response Team",
      "phones": [{
        "value": "+18199972800"
      }],
      "emails": [{
        "value":"enviroinfo@ec.gc.ca"
      }],
      "addresses": [{
        "deliveryPoint": "77 Westmorland Street, suite 260",
        "city": "Fredericton",
        "administrativeArea": "NB",
        "postalCode": "E3B 6Z4",
        "country": "Canada"
      }],
      "links": [{
        "href": "https://www.canada.ca/en/environment-climate-change.html"
      }],
      "contactInstructions": "email",
      "roles": ["producer", "host"]
  }]
  ...
}
'errors: [
    "$.properties.contacts[0].addresses[0].deliveryPoint: \'77 Westmorland Street, suite 260\' is not of type \'array\'", 
    "$.properties.contacts[0].links[0]: \'type\' is a required property"
]'

```

**Comment by josusky** [comment]
5. Distribution information
```
{
  "rel": "search",
  "type": "text/html",
  "title": "EUMETSAT Datastore",
  "href": "https://data.eumetsat.int/data/map/EO:EUM:DAT:MSG:MSG15-RSS",
  "distribution": {
    "availableFormats": [{
      "name": "native",
      "description": "This is sent in a compressed Submission Information Package (SIP) by default.",
      "numberOfFiles": "288 per day",
      "typicalFilesize": "60 MB",
      "typicalFilename": "MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip",
      "samples": "https://data.eumetsat.int/data/access/MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip",
      "documentation": {
        "rel": "alternate",
        "type": "text/html",
        "title": "SIP documentation and tools",
        "href": "https://www.eumetsat.int/formats#SIP"
      }
    }]
  }
}
```
'errors: [
  "$.links[12].distribution.availableFormats[0].samples: \'https://data.eumetsat.int/data/access/MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip\' is not of type \'object\'", 
  "$.links[12].distribution.availableFormats[0].documentation: {\'rel\': \'alternate\', \'type\': \'text/html\', \'title\': \'SIP documentation and tools\', \'href\': \'https://www.eumetsat.int/formats#SIP\'} is not of type \'array\'"
  ]'

**Comment by josusky** [comment]
If pull request #153 is approved, then what will remain is all related to time interval examples. Neither of these is considered valid:
* interval definition consisting of multiple arrays
* start/end time definition with repetition (prefix "R/")
* null start/end of the interval
The last one is obvious, the schema currently calls for a "string" value.

**Comment by amilan17** [comment]
@josusky @tomkralidis I'm not sure these changes are included the word version being prepared for publication .... I will need to review them and update the working copy that is shared with LSP.

**Comment by amilan17** [comment]
reviewed. From my perspective this issue can be closed.
