### ISSUE TITLE
Normalize WCMP2 references to artifacts such as schemas, codes...

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#158]
- Document location: https://community.wmo.int/en/wcmp2

- The normative provisions in this Standard are denoted by the URI:
- http://wis.wmo.int/spec/wcmp/2
 
- Examples provided in this specification are encoded as GeoJSON.
- Complete examples can be found at https://schemas.wmo.int/wcmp/2.0/examples
 
- The WCMP schema can be found at https://schemas.wmo.int/wcmp/2.0/wcmp2-bundled.json
 
- A link to numerous stations that the dataset is based on
- http://def.wmo.int/def/rel/wmdr/-/FacilitySet
 
- A link to a single station that the dataset is based on 
- http://def.wmo.int/def/rel/wmdr/-/EnvironmentalMonitoringFacility
 
- "url": "http://codes.wmo.int/topic-hierarchy/earth-system-discipline/weather"
- "scheme": "https://github.com/wmo-im/wis2-topic-hierarchy/blob/main/topic-hierarchy/earth-system-discipline/index.csv"
 
- The schema document will be published on http://schemas.wmo.int/wcmp/2.0 once the standard has been approved.
 
- "scheme": "http://wis.wmo.int/2012/codelists/WMOCodeLists#WMO_CategoryCode"
 
- "conformsTo": [ "http://wis.wmo.int/spec/wcmp/2/conf/core"

**Comment by amilan17** [comment]
@wmo-im/tt-wismd

**Comment by amilan17** [comment]
- http://codes.wmo.int/
   - wis

**Comment by amilan17** [comment]
As discussed with Tom, the plan is to publish to schemas.wmo.int like this: 

**Schemas site:**
- https://schemas.wmo.int/wcmp/2.0/
  -    standard
       -  PDF (from GH tag release)
  -    examples
  -    kpis
  -    shemas
  -    wcmp.zip (GH tag release, includes everything including examples)

http://www.wmo.int/spec/wcmp/2/conf/core --> this will change to wis.wmo.int/...

**Comment by tomkralidis** [comment]
Tasks:

1. Release to be deployed to https://schemas.wmo.int/wcmp/2.0 as follows:

```
|____schemas
| |____wcmp-2.0-schema.json
|____standard
| |____wcmp-2.0.pdf
|____examples
|____kpi
| |____wcmp-kpi-2.0.pdf
|____wcmp-2.0.zip. # zipfile of this directory
```

2. Change http://www.wmo.int/spec/wcmp/2/conf/core to  http://wis.wmo.int/spec/wcmp/2/conf/core

3. Update all code snippets and examples to refer to codes.wmo.int instead of github.com working repos

@wmo-im/tt-wismd

**Comment by tomkralidis** [comment]
- PR in #177
- Release process updated in https://github.com/wmo-im/wcmp2/wiki/ReleaseProcess
