### ISSUE TITLE
add source column to table for link relation selection

### ISSUE THREAD

**Issue by jsieland** [wmo-im/wcmp2#166]
In https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.html#_link_relation_selection the table combines information from IANA and wmo-codelists (https://github.com/wmo-im/wcmp2-codelists/blob/main/codelists/link-type.csv). 

It may help to add a column specifying where the corresponding link type is coming from (e.g. IANA, wmo-codelist). Otherwise it could be confusing because it seems like a duplication of information at first sight.

Any opinions?

**Comment by tomkralidis** [comment]
Added in https://github.com/wmo-im/wcmp2-codelists/pull/7
