### ISSUE TITLE
clarify specification build artifacts workflow

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#17]
A WCMP2 release will create the following artifacts:

1. specification (single HTML page, MS Word, or PDF)
2. bundled "all-in-one" schema (with no remote references)
3. JSON examples

- Item 1 will go to WMO publication process
- Items 2 and 3 should be posted to WMO infrastructure (i.e. https://schemas.wmo.int/wcmp/2.0/)

cc'ing @efucile @amilan17 for comment/validation.

**Comment by amilan17** [comment]
Thanks @tomkralidis, looks good. The specification should be output in word.

**Comment by tomkralidis** [comment]
Build artifacts workflow completed and will be posted to https://schemas.wmo.int/wcmp/2.0 for INFCOM-3.
