### ISSUE TITLE
code list for status property?

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#175]
Recommendation 10 | /rec/core/status
-- | --
A | A WCMP record SHOULD provide a properties.status property to identify the operational status of a given dataset.
B | A WCMP record SHOULD provide a properties.status.id property to identify the concept of the status (see Annex D for possible codelists to use).

**Comment by amilan17** [comment]
There are a couple of external references identified in Annex D. This Annex is not going to be in the Manual Appendix.

**Comment by tomkralidis** [comment]
TT-WISMD 2024-10-22:
- status of the dataset IM lifecycle or operational status?
- further qualify `properties.status` to help determine an appropriate codelist
