### ISSUE TITLE
add recommendation for media type when serving WCMP2

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#190]
Should we consider adding a recommendation (SHOULD) or permission (MAY) that specifies usage of [`application/geo+json`](https://www.iana.org/assignments/media-types/application/geo+json).  This would aid in broad interoperability for detecting a GeoJSON payload from an HTTP response header.

Note: we can then apply the same result to [WNM](https://github.com/wmo-im/wis2-notification-message) as required for consistency.

**Comment by josusky** [comment]
Well, we mention in the specification that both WCMP2 and WTH are based on GeoJSON. We have some examples that show links to MQTT brokers with `"type": "application/json"`. We can change those to `"type": "application/geo+json"` if you think it helps. Is it going to break anything?
