### ISSUE TITLE
Examples consistency

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#198]
I'm reviewing the examples for consistency and will use this issue to bring up questions that  I have.

**Comment by amilan17** [comment]
1. Is the links.type intended to describe the data format at that link or the type of link itself, which would mostly be "text/html".

**Comment by amilan17** [comment]
2. all records should have an created/updated dates that are in 2024

**Comment by amilan17** [comment]
3. Are there alternatives to using ISO codelists in concepts? 
e.g. 
`{
                "concepts": [
                    {
                        "id": "continual"
                    }
                ],
                "scheme": "https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_FrequencyCode"
            }`

**Comment by amilan17** [comment]
4. formats vs availableFormats
In some of the examples there is a "formats" property. While technically legal, I think the way we should do as the standard says and put this in links.distribution.availableFormats

`"formats": [ "GRIB2" ]`

**Comment by tomkralidis** [comment]
A PR is put forth in #201 .

> As discussed with Tom, the links.type property should represent what is returned when you click on the link. For example, if it's a WAF with a list of XML files then the type should be "text/html", but if clicking on the link returns an XML file, then the type should be "text/xml".

Per [RFC7303](https://www.rfc-editor.org/rfc/rfc7303.html), `text/xml` is an alias for `application/xml`, so we use the latter as required in WCMP2 and beyond.
