### ISSUE TITLE
Concepts should point to one unique and resolvable URI

### ISSUE THREAD

**Issue by GijsbertKruithof** [wmo-im/wcmp2#204]
The current standard allows for more than one concept to point to one scheme. See the example below.
This is understandable for a human being but not for a computer. So in fact this makes the metadata not machine readable. It wouldn't allow a computer to automatically link concepts to other vocabularies.
We came across this issue in the RODEO Climate Workpackage.
I would propose to make the standard more strict.
So a concept should always refer to a unique and resolvable URI. See example below.

**EXAMPLE**
The current standard allows this (example taken from https://github.com/wmo-im/wcmp2/blob/main/examples/ca-eccc-msc.daily-climate-observations.json)
```
"concepts": [
                    {
                        "id": "Climate"
                    },
                    {
                        "id": "Climate archives"
                    },
                    {
                        "id": "Climate change"
                    }
                ],
                "scheme": "https://canada.multites.net/cst"
```
This is not resolvable for a computer.

**PROPOSAL**
It should always be like this:

```
"concepts": [
			  "Total Precipitations"
			  
			],
			"scheme": "http://codes.wmo.int/bufr4/b/13/_023"
		  },
		              {
               "concepts": [
                 "Wind speed"
                 
               ],
               "scheme": "http://codes.wmo.int/common/quantity-kind/windSpeed"
            },

```
So each concept should have it's own URI which is resolvable.
Ideally it should be public (not needing a github account for instance) and it should be a persistent identifier in a controlled and maintained vocabulary.

**Comment by tomkralidis** [comment]
TT-WISMD 2024-06-28:
- WCMP2 (OGC API - Records) models concepts as objects which have the following properties:
  - `id`: required
  - `title`: optional
  - `description`: optional
  - `url`: optional
- the `url` property would be the resolvable definition
- in OGC API - Records and WCMP2, we make `url` optional to allow for concepts with or without resolvable URIs to provide flexibilty to WMO Members
- for RODEO, you could further profile the `concepts` object to override the "base" WCMP2/OGC definition by making `url` required

**Comment by tomkralidis** [comment]
Closing this issue given feedback from @wmo-im/tt-wismd.
