### ISSUE TITLE
schemas.wmo.int - Links

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wcmp2#208]
The links to schemas.wmo.int should be adapted in the documentation, e.g. 
1) http://schemas.wmo.int/wcmp/2.0  --> http://schemas.wmo.int/wcmp/2.0.0
2) https://schemas.wmo.int/wcmp/2.0/examples --> https://schemas.wmo.int/wcmp/2.0.0/examples/
3) https://schemas.wmo.int/wcmp/2.0/wcmp2-bundled.json --> https://schemas.wmo.int/wcmp/2.0.0/schemas/wcmp2-bundled.json
Thanks for checking and updating

**Comment by amilan17** [comment]
note, that these don't need to be amendments to the publications, because these links (as listed above) are not in the official WMO document.
