### ISSUE TITLE
Q from pub department on Requirements class "core"

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#226]
```
Dependency	
OGC API – Features – Part 1: Core corrigendum (OGC: OGC 17-069r)  

Preconditions	
The record conforms to OGC API – Records – Core: Part 1: Requirements Class: Record Core
```

_...I can clearly see that the official name for this standard is “OGC API – Features – Part 1: Core corrigendum”. I am trying to do a similar check for the name of the product in the next row: “OGC API – Records – Core: Part 1: Requirements Class: Record Core”. The OGC web site uses the name “OGC API - Records - Part 1: Core” (shttps://ogcapi.ogc.org/records/) which is different from the name given here. Are the words “Requirements Class: Record Core” intended to be part of the name of the standard? Any clarification you could provide would be most helpful._

**Comment by tomkralidis** [comment]
The dependency is referencing the entire standard, which defines optional Requirements Classes.  So the dependency passes.  The pre-condition specifies (exactly) which Requirements Class in OGC API - Records is assumed when specifying the WCMP2 Requirements Class.

**Comment by amilan17** [comment]
@tomkralidis 
So does it make sense to change the way the Preconditions is written to? 

Preconditions	
The record conforms to the Requirements Class “Record Core” of [OGC API - Records - Part 1: Core](https://docs.ogc.org/DRAFTS/20-004.html#clause-record-core)

**Comment by tomkralidis** [comment]
Sure.
