### ISSUE TITLE
add recommendations on granularity

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#32]
As discussed at [TT-WISMD 2022-07-13](https://github.com/wmo-im/tt-wismd/wiki/Meeting-2022-07-13#notes), WCMP2 provides an informative section on granularity.  We need normative text in the form of recommendations for clause 7.

@wmo-im/tt-wismd

**Comment by jsieland** [comment]
I think we should aim for a granularity where you get good overall information. Having said this, I personally would not go down to the variable level - as we discussed last meeting this could cause the Catalogue to be spammed by many nearly identical (only differing by the variable) metadata records.

Instead I would emphasize the possibilities of WCMP2 itself to provide further granularity within a metadata record. Following parts come to my mind: 

- using `properties.themes` (e.g. for describing variables of a model etc.)
- using templated variables in `links`-section (if possible, e.g. for a WFS)

Food for thought.

**Comment by tomkralidis** [comment]
Update TT-WISMD 2022-08-11:
- approved/merged (#36)
