### ISSUE TITLE
add GitHub Action to build standard docx and pdf in gh-pages branch

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#33]
We need a GitHub Action to build the pdf and docx representations on every push to the repository in `standard/**`
The resulting files should be in:

- https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.html
- https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.docx
- https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.pdf

cc @amilan17

**Comment by amilan17** [comment]
@tomkralidis The links above return a 404.

**Comment by tomkralidis** [comment]
Should work now?
