### ISSUE TITLE
"property" definition

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#42]
It would be useful to the reader if there was an explanation on what a "property" is. Sentences like this may be confusing for the reader: "A WCMP record SHALL provide a 'properties.providers' property".

**Comment by tomkralidis** [comment]
TT-WISMD: clarify property per JSON?  We could also use element, but it is in the tradition of XML.

Add explanation:
- properties are KVPs (values are objects or other data types)
- would be valuable to ref JSON / JSON schema specification def

**Comment by tomkralidis** [comment]
@amilan17 can we close, given https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.html#_properties as implemented in #52?

**Comment by amilan17** [comment]
good!
