### ISSUE TITLE
Remove "Core" from the mandatory conformance class name? 

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#44]
The mandatory Conformance Class for WCMP is:
•	"WMO **Core** Metadata Profile **Core**": This conformance class inherits from OGC API — Records — Part 1: Core: Requirements Class: Record Core which defines the requirements for a catalogue record. The requirements specified in the Requirements Class “Record Core" are mandatory for all implementations of WMCP. The requirements are specified in Chapter 7 and in Annex A.2 in more detail.

**Comment by tomkralidis** [comment]
TT-WISMD 2022-09-21: we need a better name.

Change to "WMO Core Metadata Profile Main"

**Comment by amilan17** [comment]
@tomkralidis I think we can close this issue.
