### ISSUE TITLE
Granularity section 

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#45]
1. The section on granularity feels incomplete and, in general, needs more explanation. 

2. Are we conflating the concepts of scope and granularity? I think scope of a WCMP2 record is a dataset and the scope of a WMDR record can be station, instrument or observation(s). Whereas, granularity is how a dataset is represented and the level of detail about a dataset in the WCMP2 record.

**Comment by tomkralidis** [comment]
TT-WISMD 2022-09-21: remove table from 6.1.3, since granularity is discussed in the scope section.

**Comment by amilan17** [comment]
removed table from editorial branch

**Comment by tomkralidis** [comment]
Thanks @amilan17

Merged/fixed.
