### ISSUE TITLE
Identifier question

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#46]
Is this the unique id of the dataset or metadata record? 

"A WCMP record utilizes the OARec id property to provide a unique identifier to a **dataset**. A record identifier is essential for querying and identifying **records** within the GDC."

**Comment by tomkralidis** [comment]
TT-WISMD 2022-09-21:

- id is of the metadata record
- metadata record describes the dataset (see Scope)

- "A WCMP record utilizes the OARec id property to provide a unique identifier to a metadata record. An identifier is essential for querying and identifying dataset records within the GDC."

**Comment by tomkralidis** [comment]
@amilan17 let me know if there are further questions or whether this should be closed.
