### ISSUE TITLE
question on 7.1.2 Granularity section

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#47]
It looks like this section describes best practices for representing granularity in 7.1.9 Themes, it doesn't provide information about the structure of the standard. Should it be moved into 7.1.9?

**Comment by tomkralidis** [comment]
TT-WISMD 2022-09-21:

- move JSON examples in 7.1.2 to 7.1.9
- delineate between hard property definitions and others (validation, granularity)

Decision
- move 7.1.2 explanation to informative text
- move 7.1.2 examples and recommendations to 7.1.9

**Comment by amilan17** [comment]
reminder...

**Comment by tomkralidis** [comment]
Fixed in #77
