### ISSUE TITLE
Type question

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#49]
Verify that there are two types of "type". 

1. 7.1.1. Validation 
   * "type" with value of "Feature"
3. 7.1.5. Properties Type
   * "properties.type" with value of "Dataset" or "Service"

**Comment by tomkralidis** [comment]
TT-WISMD 2022-09-21:
- needs a codelist?
- fix to codelist of type with `dataset`
- codelist can grow over time, in theory

**Comment by tomkralidis** [comment]
TT-WISMD 2023-05-05:
- initial list at https://github.com/wmo-im/wcmp2-codelists/blob/main/codelists/resource-type.csv

ACTION @amilan17 to review current specification updates.

**Comment by amilan17** [comment]
I think it's more clear now.
