### ISSUE TITLE
Clarification of terminology used

### ISSUE THREAD

**Issue by steingod** [wmo-im/wcmp2#60]
A clear definition of what is a requirement and what is a recommendation  (or even permission) in the document is currently missing although both are widely used. A clear and distinct clarification of terminology used simplifies uptake of the document and reduces misinterpretations.

**Comment by amilan17** [comment]
+1 - we need a summary table of the standard

**Comment by tomkralidis** [comment]
We use a subset of [RFC2119](https://www.rfc-editor.org/rfc/rfc2119):
- Requirement: SHALL
- Recommendation: SHOULD
- Permission: MAY

Would a reference to the RFC be helpful, or do we need more?

cc'ing @golfvert for comment, here given we have used the above terms (though we have not specified them concretely). We will want a consistent approach with similar documentation/specifications.

cc @efucile

**Comment by steingod** [comment]
A reference is good, but better include sufficient information to read the document without consulting all potential references. I would prefer the suggestion by @amilan17 above.

**Comment by tomkralidis** [comment]
@steingod we have since added a summary table of elements in https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.html#_the_wmo_core_metadata_profile_record (Table 2).  There is also a pending PR to add links from each element to its definition for easier (HTML) navigation. Let me know if that works for you?

**Comment by steingod** [comment]
@tomkralidis yes this is fine. Some specific comments, I assume properties.type refers to a WMO resource. If so probably best to specifically state so as resource is used in different contexts in the document. And in section 7.1.17 it states: 

> The additionalConditions property are access and license details that apply when the dataset is classified as recommended.

According to the WMO Unified Data Policy a license in the form of attribution is not considered a condition and these datasets can still be a core dataset. This should be updated.

**Comment by tomkralidis** [comment]
Proposed update to data policy:

"
Licensing and copyright are expressed via the `links` property (see distribution section), providing access, license and attribution details as required.  Conditions on use are essential for the WMO Unified Data Policy, but for transparency and clarification any other conditions should also be indicated.
"

**Comment by tomkralidis** [comment]
The text in https://github.com/wmo-im/wcmp2/issues/60#issuecomment-1557030181 has been added to the specification.
