### ISSUE TITLE
require 3 types of providers

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#66]
I think there should be 3 types of contacts required. point of contact for the distrubution of the dataset and metadata contact for the creation of the record. The other provider should be the originator of the dataset, but in my experience from working at an archive, the originator is no longer "in charge" of the dataset and it was often included without contact information.

**Reference**

[https://github.com/wmo-im/wcmp2/blob/main/standard/requirements/core/REQ_providers.adoc](https://github.com/wmo-im/wcmp2/blob/main/standard/requirements/core/REQ_providers.adoc)

current REQ. B: "A WCMP record `properties.providers` property SHALL provide at least TWO providers (as multiple provider objects or a single provider object with multiple roles) based on the metadata point of contact and the originator of the data. Providers are defined as either a URI or inline."

**Comment by tomkralidis** [comment]
TT-WISMD 2023-05-05: decide which roles to define and whether we can reuse / leverage any form https://github.com/opengeospatial/ogcapi-records/blob/master/core/standard/annex_contact_roles.adoc or elsewhere.

ACTION: @gaubert to investigate and provide recommendation.

**Comment by tomkralidis** [comment]
TT-WISMD 2023-06-22
- closing as discussed given #109
