### ISSUE TITLE
Remove references to services?

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#67]
I think we should remove services in explanatory text since this standard is focused on describing data as defined in the WMO data policy (Resolution 1). Alternatively, we can rephrase, for e.g, "data and their services".

\-- 

#### 6.1.3. Granularity

In order to provide discovery metadata of value, it is important to clarify the granularity levels of which providers are to provide describing their data/~services~. Articulating the level of granularity will reduce catalogue "pollution" and bring the user closer to the data via their search criteria.

7.1.6. Properties Type
WCMP records provide descriptive information about different resource types, such as dataset or **services**.

**Comment by tomkralidis** [comment]
Addressed in #70
