### ISSUE TITLE
Consider making record update date optional

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#68]
Make this field optional or add guidance about how to use when the record is first created and doesn't have an update yet. 

#### 7.1.16. Record Update Date

A WCMP record has a `properties.recordUpdated` property, which describes the date that the record was last updated.

```json
"recordUpdated": "2022-06-12T18:52:39Z"
```

<table><tbody><tr><td><strong>Requirement 12</strong></td><td><strong>/req/core/record_update_date</strong></td></tr><tr><td>A</td><td>A WCMP record SHALL provide a <code>properties.recordUpdated</code> property.</td></tr></tbody></table>

**Comment by tomkralidis** [comment]
Addressed in #70
