### ISSUE TITLE
provide user stories for discovery metadata

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#7]
As part of the [next version of WCMP](#101), we need to identify [user stories](https://www.mountaingoatsoftware.com/agile/user-stories) that capture goals and acceptance criteria.  The user stories will capture what a user does/needs as part of their work, and will help clarify user needs as we continue to assess metadata standards.

**Comment by amilan17** [comment]
@tomkralidis I think we can close this

**Comment by tomkralidis** [comment]
User stories are included in WCMP2 at https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.html#_user_stories
