### ISSUE TITLE
simplify descriptions of conformance classes

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#73]
Change descriptions like: 
"A WCMP record has a _properties.description_ property, which is a free-text summary description of the dataset."
to 
"The _description_ property is a free text summary of the dataset."

**Comment by amilan17** [comment]
Attached is my first stab at updating the language describing the conformance classes of WCMP2. 
[wcmp2-DRAFT-amEdits.docx](https://github.com/wmo-im/wcmp2/files/10076963/wcmp2-DRAFT-amEdits.docx)

**Comment by tomkralidis** [comment]
Addressed in #74
