### ISSUE TITLE
Define WCMP2 KPIs

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#79]

**Comment by tomkralidis** [comment]
An initial skeleton has been put forth in #90 for TT-WISMD discussion/approval.

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-13
- ACTION: build out KPIs as CI workflow to GitHub Pages
- review KPIs
 - update contacts
 - links health
   - for realtime links (MQTT), check that the link `channel` is valid
 - ACTION: add to WIS2 Guide
   - information management: metadata curation SHOULD be at least every 6 months
   - GDC SHOULD run validation/KPI checks once a month
   - what failed
   - how metadata grades against KPIs

**Comment by tomkralidis** [comment]
Update: CI workflow now includes KPI generation, and is now available at https://wmo-im.github.io/wcmp2/

**Comment by tomkralidis** [comment]
As well, related discussion in https://github.com/wmo-im/wis2-guide/issues/15 (@antje-s to take a first pass for metrics definition).

**Comment by antje-s** [comment]
Added a first proposal
https://github.com/wmo-im/wis2-metric-hierarchy/blob/main/metric-hierarchy/gdc.csv

**Comment by tomkralidis** [comment]
TT-WISMD 2023-10-06:
- @antje-s to provide example OpenMetrics payload

**Comment by tomkralidis** [comment]
KPIs updates by @jsieland completed (thanks Julia!)

**Comment by tomkralidis** [comment]
GDC [metrics](https://github.com/wmo-im/wis2-metric-hierarchy/blob/main/metric-hierarchy/gdc.csv) implemented and [example](https://github.com/wmo-im/wis2-guide/issues/15#issuecomment-1797967879) provided by @antje-s (thanks Antje!).

**Comment by tomkralidis** [comment]
TT-WISMD 2024-01-15:
- @amilan17 to review for inclusion into WIS2 Guide
- then close this issue

**Comment by tomkralidis** [comment]
Initial KPIs defined, structure updated by @amilan17 and will be included in the Manual.

**Comment by amilan17** [comment]
> Initial KPIs defined, structure updated by @amilan17 and will be included in the Manual. 

included in the Manual instead of the Guide?

**Comment by tomkralidis** [comment]
Sorry yes Guide :)
