### ISSUE TITLE
table view of wcmp2

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp2#80]
Provide a view of the standard in tables such that each property in a property object is listed including the conditionality and type of content allowed.
For example: 

|Property|Type|Requirement|Description|
|:----|:----|:----|:----|
|id|string|required|A unique identifier to the dataset|
|type|string (code)|required|A fixed value denoting the record as a GeoJSON Feature|
|conformsTo|string (URL)|required|The version of WCMP associated that the record conforms to|
|geometry|object|required|Geospatial location associated with the dataset, in a geographic coordinate reference system|
|time|object|required|Temporal extent associated with a dataset|
|additionalExtents|object|optional| |
|links|object|required|Online linkages to data retrieval or additional resources associated with the dataset|properties||object|required| |

 
## geometry object
|Property|Type|Requirement|Description|
|:----|:----|:----|:----|
|geometry|object|required|Geospatial location associated with the dataset, in a geographic coordinate reference system|
|type|string (code)|required|point, polygon,...?|
|coordinates|array (numbers)|required| |

**Comment by amilan17** [comment]
I think this is related to issue #60

**Comment by tomkralidis** [comment]
Closing in lieu of #60.
