### ISSUE TITLE
clarify topic hierarchy

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#82]
Currently, WMO topic hierarchy is expressed as a theme/concept as follows:

```json
{
  "concepts": [
    {
      "id": "wis2/CAN/eccc-msc/data/core/weather/surface-based-observations"
    }
  ],
  "scheme": "https://github.com/wmo-im/wis2-topic-hierarchy"
}
```

As discussed during [TT-WISMD 2022-12-16](https://github.com/wmo-im/tt-wismd/wiki/Meeting-2022-12-16), given 1..n concepts are allowed, the model potentially allows for 1..n topics to be applied to a dataset. We need to apply one topic to a dataset.

Should we strongly define the topic hierarchy with `properties.wmo:topicHierarchy` (single string value)?  This would eliminate any ambiguity, and remove the need to define the `scheme` (which would be implied).  Example:

```json
"properties": {
  
  "wmo:topicHierarchy": "wis2/CAN/eccc-msc/data/core/weather/surface-based-observations"

}
```

cc @wmo-im/tt-wismd

**Comment by josusky** [comment]
As the topic hierarchy (or data ID hierarchy) is a central concept in WIS 2.0, it seems logical to me to have it as a dedicated property rather than buried among other concepts. But that is an opinion of a software developer dinosaur that likes to see O(1) complexity instead of O(n).

**Comment by tomkralidis** [comment]
As discussed at TT-WISMD 2023-01-11:
- cardinality?
- dataset collection?
- granularity?
  - WCMP2 topic is broadest
  - WNM is most specific, including filename (`data_id`)
- WCMP2 can provide a broader topic (while topics can be more granular)
- change name of element
- WCMP2 has topics in two areas:
  - topic identification (**TBD** or leave as `wmo:topicHierarchy`) (no infrastructure prefix)
  - MQTT binding / subscription (`links.*.wmo:topic`) with full infrastructure prefix
- should we have only `links.*.wmo:topic`?  Can be dangerous (infrastructure) for present workflow
  - future proof to keep distinct (they just happen to be very similar currently)

Decision is to keep separate for WIS2 pilot phase and evaluate.

**Comment by tomkralidis** [comment]
Related: #86 and #87
