### ISSUE TITLE
change link wmo:topic to channel

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#86]
The OGC MetOceanDWG is working on a discussion paper on PubSub in OGC API standards.  AsyncAPI is a key component of the recommendations of the discussion paper.  It is hoped that the discussion paper will result in efforts for an OGC API - PubSub standard.

AsyncAPI is a PubSub complement to OpenAPI and allows for abstraction of PubSub protocols (MQTT, AMQP, etc.).  AsyncAPI abstracts the MQTT term "topic" for "channel", in support of multiple PubSub protocols.  See https://www.asyncapi.com/docs/concepts/channel for more information.

In WCMP2, we provide link objects with an optional `wmo:topic` property to be able to convey the MQTT topic that is related to the dataset.

To align with AsyncAPI as well as the directions in OGC future plans and broader interoperability, propose to change as follows:

Current:
```json
        {
            "rel": "OASIS:MQTT",
            "href": "mqtts://example.org",
            "wmo:topic": "cache/a/wis2/can/eccc-msc/data/core/weather/observations/surface-land/landFixed",
            "type": "application/json",
            "title": "Data notifications"
        }
```
Proposed:
```json
        {
            "rel": "OASIS:MQTT",
            "href": "mqtts://example.org",
            "channel": "cache/a/wis2/can/eccc-msc/data/core/weather/observations/surface-land/landFixed",
            "type": "application/json",
            "title": "Data notifications"
        }
```

@jsieland @josusky @gaubert @Amienshxq @solson-nws comments?

**Comment by josusky** [comment]
I don't particularly like the idea of using the word "channel" as it is used for many other things. But I understand that finding a word that fits all possible protocols is not easy. As long as we properly document it, it can be called whatever. I suggest we add detailed descriptions/examples for other protocols too, not just MQTT. For example, for AMQP, we have the following example at the moment (note the `exchange`):
```            {
                "protocol": "amqps",
                "title": "WIS Message System GISC Offenbach",
                "broker": "https://oflkd013.dwd.de",
                "exchange": "wisof",
                "topic/routing_key": "v03/wis/de/offenbach/surface/aviation/metar/de"
            }
```
Shall it be changed to:
```            {
                "rel": "<something>amqps",
                "href": "https://oflkd013.dwd.de/wisof",
                "channel": "origin/a/wis2/deu/offenbach/data/core/weather/..."
                "title": "WIS Message System GISC Offenbach",
            }
```
or
```           {
                ...
                "href": "https://oflkd013.dwd.de",
                "channel": "wisof/origin/a/wis2/deu/offenbach/data/core/weather/..."
                ...
            }
```
or perhaps the channel value should be `wisof/origin.a.wis2.deu.offenbach.data.core.weather..."`?

**Comment by tomkralidis** [comment]
+1 to document clearly in WCMP2.  In WCMP2, while we are prioritizing on MQTT per WIS2, an AMQP example could be:

```json
            {
                "rel": "download",
                "href": "amqps://oflkd013.dwd.de",
                "channel": "wisof.origin.a.wis2.deu.offenbach.data.core.weather/#"
                "title": "WIS Message System GISC Offenbach",
            }
```

- realizing `rel` should really be an IANA link relation or extension (`items` is an official link relation per OGC API - Features and OGC API - Records)
- the channel value is opaque (in the AsyncAPI context), so we can separate/delimit per the protocol requirements
- where `wisof` lands in the aboe (suffix of `href` or beginning of `channel`)

Thoughts @josusky?

**Comment by josusky** [comment]
As discussed over Slack, let's keep protocol-specific things in the `href`, we might see there various strange things in some cases, and keep `channel` for the part that is more or less the same everywhere. I am still not fully OK with the term `channel` as that has a lot of meanings, but I must admit that `topic` has the same problem.

**Comment by petersilva** [comment]
The protocols are different, even conceptually, there are things that do not map.  "The part that is the same everywhere" should include a flexible topic root, that will likely be interpreted differently by different protocols.

* in AMQP 0.9 one publishes to "Exchanges" ... (the wisof in the example above.)
* The word for what rabbitmq calls "Exchange" ... in Kafka and Azure's AMQP is  "Topic" ... they are not hierarchical, but simple flat names. no wildcards.  those two protocols have no hierarchical topics.  
* in AMQP (topic exchanges only)  there are hiearchical topics, similar to MQTT, but a good mapping of MQTT <-> AMQP involves prefixing the topic hierarchy with an exchange name. 
* rabbitmq defines the thing after the hostname (first path element) as a vhost in their URI's.  ( https://www.rabbitmq.com/uri-spec.html ) so an exchange name there conflicts with current practice... plus... where do people put vhost specifications?

in MQTT, the topic is everything you need to describe where you are posting to.  in other protocols you have an additional root of the topic tree.  So there is no protocol independent way to specify things... I expect having the exchange at the beginning of the *channel* would be more useful and flexible in practice:

```
                href": "amqps://oflkd013.dwd.de/",   <--- vhost could be added here, conforms to rabbitmq URI practice.
                "channel": "wisof.origin.a.wis2.deu.offenbach.data.core.weather.#"

```

* exchange is the root of the topic tree... encoded as the first element of the channel.
* Kafka and MS Azure would map the same entity to what they call a "Topic"
* on mqtt, it's just the root of the topic tree... having multiple topic roots is useful for:
  * publishing for different audiences, potentially different permissions (authentication by sub-tree.)
  * publishing pre-standard data (not operational yet...) it will look like that

in current practice, exchanges are used frequently, and losing that flexibility in the standard would be a loss.

* fwiw... in AMQP 0.9 one establishes a connection, and then sets up a *channel* within it... one can have multiple *channels* per connection.

**Comment by antje-s** [comment]
Caution with the example...currently we don't have rabbitMQ running as WIS2 pilot anymore, because the decision for only MQTT(S) as protocol was made. The test server for the demonstration projects (oflkd013) is also no longer running. For the pilot phase we switched to wis2 for MQTT(S) broker

An extension for exchange at the start of the topic/channel-value should not cause problems and probably increases flexibility, but actually goes against the decision for exclusively MQTT. If it will be added it should also be included in https://github.com/wmo-im/wis2-topic-hierarchy

**Comment by tomkralidis** [comment]
WCMP2 PR in #87
