### ISSUE TITLE
validate identifier and topic hierarchy similarities

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp2#92]
@wmo-im/tt-wismd : while implementing the [WCMP2 ETS in pywcmp](https://github.com/wmo-im/pywcmp/pull/93), the following was flagged/noticed:

A WCMP2 record's `id` [is defined](https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.html#_identifier) by using some of the same constructs of `properties.wmo:topicHierarchy`.  Example:

identifier:
```json
"id": "urn:x-wmo:md:can:eccc-msc:observations.swob"
```
topic hierarchy:
```json
"wmo:topicHierarchy": "origin/a/wis2/can/eccc-msc/data/core/weather"
```

Requirements 2C and 2D specify validating part of the identifier against the topic hierarchy for the country and centre-id components/values.

Does a WCMP2's identifier (`id`) need to have a format/convention, or can/should it be, say, a GUID?

**Comment by josusky** [comment]
Isn't this related to issue #46 ? 
I think, the fewer duplicities, the better. 
As the `id` will be used, optionally so far, (https://github.com/wmo-im/wis2-notification-message/issues/25) in the data notifications to link back to metadata, I would prefer a more human-friendly identifier. UUIDs should be used for some internal machinery.

**Comment by amilan17** [comment]
In my opinion, I think GUID is sufficient, however, what would be a reason to use the TH in the metadata id?

**Comment by amilan17** [comment]
@tomkralidis I think we can close this issue, because we decided to NOT require TH in the identifier.
