### ISSUE TITLE
Is it possible to add multiple topicHierarchy?

### ISSUE THREAD

**Issue by steingod** [wmo-im/wcmp2#94]
It is not clear to me if it is possible to add multiple topicHierarchy from the current version of WCMP version 2 documentation. The section on properties/themes states that "A WCMP metadata record can have one or more themes.". Such statements would be good to have for all elements so it is possible to easily understand how to use the standard.

For the cryosphere applications I think multiple topicHierarchy would be necessary for this element to be useful as much of the information would fit under weather, climate etc as well.

**Comment by tomkralidis** [comment]
Closing in lieu of #95
